# ==========================================
# HYPRPAPER CONFIG
# ==========================================
# Taruh wallpaper lo di ~/Pictures/wallpaper.jpg
# Ganti path di bawah sesuai lokasi file wallpaper

preload = ~/Pictures/wallpaper.png

# Set wallpaper ke semua monitor (kosong = semua)
wallpaper = , ~/Pictures/wallpaper.png

# Splash screen off
splash = false
