# ==========================================
# HYPRPAPER CONFIG
# ==========================================

# Preload wallpaper
preload = /home/juang/Pictures/wallpaper.png

# Apply to all monitors (empty string = all)
wallpaper = ,/home/juang/Pictures/wallpaper.png

splash = false
ipc = true
