# ==========================================
# HYPRPAPER CONFIG
# ==========================================

# Preload wallpaper
preload = ../../wallpaper.png

# Apply to all monitors (empty string = all)
wallpaper = ../../wallpaper.png

splash = false
ipc = true
